database:
    build: database
site:
    build: site
    command: yesod devel # dev setting
    # command: /opt/server/dist/build/locked-booking/locked-booking # production
    environment:
        - HOST=0.0.0.0
        - PGHOST=database
        - PGPORT=5432
        - PGUSER=postgres
        - PGPASS
        - PGDATABASE=postgres
        - FB_APPID=924467847625184
        - FB_APPSECRET
    links:
        - database
    tty:
        true # dev setting
    # tty:
    #     false # production
    ports:
        - "3000:3000" # dev setting
    volumes:
        - ./site:/opt/server/
