PleaseFillInFormInfo: Xin vui lòng điền đầy đủ thông tin
PlaceBooking: Đặt chỗ
Name: Họ tên
Email: Email
Phone: Số điện thoại
NumberOfPeople: Số người
Reserved: Đã đặt chỗ
Close: Thoát
Difficulty: Độ khó
RecommendedNumberOfPeople minPeople@Int maxPeople@Int: #{show minPeople} đến #{show maxPeople} người chơi 
Timeslot: Thời gian
InvalidBookingData: Invalid booking data
Error: Lỗi
TimeslotBooked: Khung giờ đã có người đặt
DatabaseError: Lỗi cơ sở dữ liệu, xin thử lại sau
FormMissing: Không nhận được dữ liệu
